# Model hyperparameters
model:
  name: "taxocapsnet"
  version: "v1.0"
  
training:
  batch_size: 32
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 0.0001
  
data:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  shuffle: true
  random_seed: 42

inference:
  batch_size: 16
  device: "cuda"
